/* eslint-disable @typescript-eslint/no-var-requires */
const { pick, omit } = require("lodash")
const colors = require("tailwindcss/colors")
const defaultTheme = require("tailwindcss/defaultTheme")

/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                },
                coastal: {
                    blue: {
                        10: '#0388A6',
                        9: 'hsla(191, 96%, 33%, 0.9)',
                        8: 'hsla(191, 96%, 33%, 0.8)',
                        7: 'hsla(191, 96%, 33%, 0.7)',
                        6: 'hsla(191, 96%, 33%, 0.6)',
                        5: 'hsla(191, 96%, 33%, 0.5)',
                        4: 'hsla(191, 96%, 33%, 0.4)',
                        3: 'hsla(191, 96%, 33%, 0.3)',
                        2: 'hsla(191, 96%, 33%, 0.2)',
                        1: 'hsla(191, 96%, 33%, 0.1)',
                    },
                },
                sandy: {
                    beige: {
                        10: '#F2D5C4',
                        9: 'hsla(22, 64%, 86%, 0.9)',
                        8: 'hsla(22, 64%, 86%, 0.8)',
                        7: 'hsla(22, 64%, 86%, 0.7)',
                        6: 'hsla(22, 64%, 86%, 0.6)',
                        5: 'hsla(22, 64%, 86%, 0.5)',
                        4: 'hsla(22, 64%, 86%, 0.4)',
                        3: 'hsla(22, 64%, 86%, 0.3)',
                        2: 'hsla(22, 64%, 86%, 0.2)',
                        1: 'hsla(22, 64%, 86%, 0.1)',
                    },
                },
                seafoam: {
                    green: {
                        10: '#32D9C8',
                        9: 'hsla(174, 69%, 52%, 0.9)',
                        8: 'hsla(174, 69%, 52%, 0.8)',
                        7: 'hsla(174, 69%, 52%, 0.7)',
                        6: 'hsla(174, 69%, 52%, 0.6)',
                        5: 'hsla(174, 69%, 52%, 0.5)',
                        4: 'hsla(174, 69%, 52%, 0.4)',
                        3: 'hsla(174, 69%, 52%, 0.3)',
                        2: 'hsla(174, 69%, 52%, 0.2)',
                        1: 'hsla(174, 69%, 52%, 0.1)',
                    },
                },
                aquamarine: {
                    serenity: {
                        10: '#0FBFBF',
                        9: 'hsla(180, 85%, 40%, 0.9)',
                        8: 'hsla(180, 85%, 40%, 0.8)',
                        7: 'hsla(180, 85%, 40%, 0.7)',
                        6: 'hsla(180, 85%, 40%, 0.6)',
                        5: 'hsla(180, 85%, 40%, 0.5)',
                        4: 'hsla(180, 85%, 40%, 0.4)',
                        3: 'hsla(180, 85%, 40%, 0.3)',
                        2: 'hsla(180, 85%, 40%, 0.2)',
                        1: 'hsla(180, 85%, 40%, 0.1)',
                    },
                },
                turquoise: {
                    mist: {
                        10: '#0BADBF',
                        9: 'hsla(186, 89%, 40%,0.9)',
                        8: 'hsla(186, 89%, 40%,0.8)',
                        7: 'hsla(186, 89%, 40%,0.7)',
                        6: 'hsla(186, 89%, 40%,0.6)',
                        5: 'hsla(186, 89%, 40%,0.5)',
                        4: 'hsla(186, 89%, 40%,0.4)',
                        3: 'hsla(186, 89%, 40%,0.3)',
                        2: 'hsla(186, 89%, 40%,0.2)',
                        1: 'hsla(186, 89%, 40%,0.1)',
                    },
                },
                multicolore: {
                    pink: '#F56991',
                    orange: '#F7971E',
                    yellow: '#FFC107',
                    green: '#4CAF50',
                    lightblue: '#03A9F4',
                    blue: '#3F51B5',
                    purple: '#9C27B0',
                    black: '#212121',
                },
            },
            fontFamily: {
                body: [
                    'Inter',
                    'ui-sans-serif',
                    'system-ui',
                    '-apple-system',
                    'system-ui',
                    'Segoe UI',
                    'Roboto',
                    'Helvetica Neue',
                    'Arial',
                    'Noto Sans',
                    'sans-serif',
                    'Apple Color Emoji',
                    'Segoe UI Emoji',
                    'Segoe UI Symbol',
                    'Noto Color Emoji',
                ],
                sans: [
                    'Inter',
                    'ui-sans-serif',
                    'system-ui',
                    '-apple-system',
                    'system-ui',
                    'Segoe UI',
                    'Roboto',
                    'Helvetica Neue',
                    'Arial',
                    'Noto Sans',
                    'sans-serif',
                    'Apple Color Emoji',
                    'Segoe UI Emoji',
                    'Segoe UI Symbol',
                    'Noto Color Emoji',
                ],
            },
            borderWidth: {
                DEFAULT: '1px',
                0: '0',
                2: '2px',
                3: '3px',
                4: '4px',
                6: '6px',
                8: '8px',
            },
            minHeight: {
                ...defaultTheme.height,
            },
            minWidth: {
                ...defaultTheme.width,
            },
        },
    },
    plugins: [require('tailwind-scrollbar-hide')],
    future: {
        hoverOnlyWhenSupported: true,
    },
};
